name: ci

on:
  push:
    branches:
      - master
    tags:
      - 'macos-[0-9]+.*'
  pull_request:
  workflow_dispatch:

env:
  MOZC_SHA: ce1fb7fe48efb1d85f8e54eff1b05e9e692bf0d4

jobs:
  lint:
    runs-on: ubuntu-latest
    outputs:
      MOZC_SHA: ${{ env.MOZC_SHA }}
      message: ${{ steps.commit-message.outputs.message }}
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-python@v6
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: pip install ruff pyright dirhash

      - name: Lint
        run: |
          ruff check scripts
          pyright scripts/*.py

      - name: Pass commit message
        id: commit-message
        run: |
          if [[ "${{ github.event_name }}" == 'pull_request' ]]; then
            echo "message=${{ github.event.pull_request.title }}" >> "$GITHUB_OUTPUT"
          elif [[ "${{ github.ref }}" == 'refs/heads/master' ]]; then
            message=$(echo "${{ github.event.head_commit.message }}" | head -n 1)
            echo "message=$message" >> "$GITHUB_OUTPUT"
          else
            echo "message=!windows!js" >> "$GITHUB_OUTPUT"
          fi

  macos:
    if: "!contains(needs.lint.outputs.message, '!macos')"
    needs: lint
    uses: ./.github/workflows/macos.yml
    with:
      mozc_sha: ${{ needs.lint.outputs.MOZC_SHA }}

  windows:
    if: "!contains(needs.lint.outputs.message, '!windows')"
    needs: lint
    uses: ./.github/workflows/windows.yml

  js:
    if: "!contains(needs.lint.outputs.message, '!js')"
    needs: lint
    uses: ./.github/workflows/js.yml
    with:
      mozc_sha: ${{ needs.lint.outputs.MOZC_SHA }}
