name: ci

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install ruff pyright dirhash

      - name: Lint
        run: |
          ruff check scripts
          pyright scripts/*.py

  macos:
    if: "!contains(github.event.head_commit.message, '!macos')"
    needs: lint
    uses: ./.github/workflows/macos.yml

  js:
    if: "!contains(github.event.head_commit.message, '!js')"
    needs: lint
    uses: ./.github/workflows/js.yml
